# Generated by Django 3.1.7 on 2022-09-08 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('weight', models.DecimalField(decimal_places=2, help_text='1-2 (lbs)', max_digits=3, validators=[django.core.validators.MinValueValidator(0, message='Cannot have zero weight')])),
                ('stock', models.PositiveSmallIntegerField(default=0, help_text='Current supply')),
                ('price', models.DecimalField(decimal_places=2, help_text='Mark up price', max_digits=10)),
            ],
        ),
    ]
