# Generated by Django 3.1.7 on 2022-09-09 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
